spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://47.101.34.15:3306/soft?useSSL=true&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    username: root
    password: ${MYSQL_PASSWORD}
  rabbitmq:
    host: 47.101.34.15
    port: 5672
    virtual-host: SoftwareCooperativeEngineering
    username: sce
    password: ${RABBIT_PASSWORD}
  data:
    redis:
      host: 47.120.49.22
      port: 6379
      database: 2
      password: ${REDIS_PASSWORD}

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.softwarecooperative.softwareciooperative.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

logging:
  config: classpath:logback-spring.xml

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.softwarecooperative.softwarecooperative.pojo.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

backend:
  # 名称
  name: SoftwareCooperativeDesign
  # 版本
  version: 0.0.1
  # 版权年份
  copyrightYear: 2024
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/sc/uploadPath，Linux配置 /home/sc/uploadPath）
  profile: D:/sc/uploadPath/
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数字计算 char 字符验证
  captchaType: math
  # 前台转发路径
  render: http://localhost
  # rsa公钥
  publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArv21X8y5+vL0PYTNAzxqZTsUTQzDiStxipxda5phU46WaIpMYmr9PR0KRavEBKEHVRsaw4hYU9WJoUJOIfdl8xSuYlVG0aBQK/gEarvhoJZz63lj/Qjn1xwR5SKQD/sxh/Iyl+XbRw4KYbPPXHGvCx7sv01CE01SzB8o7APCcAHkOmr9QH2gQtmH+Ew2ryZlwSKA2i1Tw6mdoTe5vrZaBpjM17497dI2rdMkN7WpzhEe4WYWn4YHfqYrhJEgMwi2A61ZPGyJi8KlpB2xK5NZLE495d+fwOGfeX1bCr3UkImK3s9YpzPPpvz/YpvRsnpEbKokovi6lqFS1cJR9NjI8QIDAQAB
  # rsa私钥
  privateKey: MIIEuwIBADANBgkqhkiG9w0BAQEFAASCBKUwggShAgEAAoIBAQCu/bVfzLn68vQ9hM0DPGplOxRNDMOJK3GKnF1rmmFTjpZoikxiav09HQpFq8QEoQdVGxrDiFhT1YmhQk4h92XzFK5iVUbRoFAr+ARqu+GglnPreWP9COfXHBHlIpAP+zGH8jKX5dtHDgphs89cca8LHuy/TUITTVLMHyjsA8JwAeQ6av1AfaBC2Yf4TDavJmXBIoDaLVPDqZ2hN7m+tloGmMzXvj3t0jat0yQ3tanOER7hZhafhgd+piuEkSAzCLYDrVk8bImLwqWkHbErk1ksTj3l35/A4Z95fVsKvdSQiYrez1inM8+m/P9im9GyekRsqiSi+LqWoVLVwlH02MjxAgMBAAECgf8BbHa5yz46kkNdiE6bNloI+20SpKM1r8D7zCqc/Tx5Bc7DJbOQcq007gXoYlOL+206J/qZGx21XbYKg420wItajt8Rky90U/YbnlQo/o/ItkomP/1guHbIPl2DHqr5uo/xNCJuJ1UGAAkD4GSCannqGbzuPzuFU4uvU3RcaUbEwBiWQxoaihhe2C6F2GV/rsZ3s3F6WoHCDsULf5O9FvwK6nHizXiMMHgKPTlwsi9j2OWJqoJ1AkObP1s8WxHEixQ3GDKgZtOlnH+5tVYOAMh712tzdSaVzLMupfsJNnndbVP72cT1xzK8WLkVfFvekznbSXC9DrSDVL+GgEWeeDsCgYEAx1DTj6xjRV3H79sHyB8sBKiLr8HSJS+FDZ+lOfC5t/iqS9ydsg9KHHPKKVYFzzpeB0H7PCbMJAuESzbj9z/hR00R+JeMMuKcsBy046pOq7uQtXbGpGm6u2OJobnZVm0uU0sq7PgrGfbjEm7wkxI6fcyvSC/wAChkMU49AifPwHsCgYEA4MHsvjA6eyXOfCUlGiG0lZSSN/NUWdXImrN53stqKn3JPfl/fb2n0E6fISzhB093BZHrF8RJjd56yyiwQ1ExQFUxM+D8v5j8mKNM71khdz5ici9cDk9mSgPgH/5PEmptr+0GQZAxB2acQjhQLKUz2eWJQeL2NeL6+oBkL8mqvoMCgYAntPJwrOcZ6pTqM7hZJdyfEPTDDtnOjqjzDdrcsBhPjjpe4pSH5IPfJzIfCgQeRIJ2764dTZ1dkO3KDiVcHF3E1pW98HL9sCeG7jEbKdKCY9twSzlHh8irjCjfDyc9EIMqFM94ZfgwM/8IrRFAO2Frrls9Bk/JuEI9kFiXFVdOAQKBgQC34M//9VMTByY8WONW0rZ8HdXWYoPjD00Ui7sr9D2CT/CBfIq6Y5xUhs4XhTEBGxkj/HJaumL250qMxVgXauihWlFrwSjm05HsisVZmBESDn7aLjbhGkJ0UWFeq18jkOD2KjORFheWl3NFle6559pY7TpzJe0Kvw1YPgw5MIM5YwKBgAgjUh49itu+VCW70MQNuZCoZoG9KLWwLXFxXOnzf8REbLytFDnKtcRlbWDBxU8lKM6QBgsA3ycygGLa+cwXBnt1Nt2xNtNR1xVZp9ciZBaLcBHctXway+mtQY+sEec5Jv01X1zMn0wdwa/QgIy83y8uglQVL2nSFtipmWcRAA8c

aliyun:
  oss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    # 使用环境变量配置
    access-key-id: ${OSS_ACCESS_KEY_ID}
    access-key-secret: ${OSS_ACCESS_KEY_SECRET}
    bucketName: software-cooperative-engineering