@startuml
package com.softwarecooperative.softwareciooperative.mq {
    class ChatRecordListener {
        -chatRecordRepo: ChatRecordRepo
        -scheduler: ScheduledExecutorService
        -buffer: List<ChatRecord>

        +ChatRecordListener()
        +receiveMessage(message: String): void
        -saveMessages(): void
    }
}

package com.softwarecooperative.softwareciooperative.dao.repository {
    interface ChatRecordRepo {
        +insert(entity: S): S
        +insert(entities: Iterable<S>): List<S>
        +findByGroupId(groupId: Integer, pageable: Pageable): Page<ChatRecord>
    }
}

ChatRecordListener --> ChatRecordRepo

@enduml
